language: python

python:
  - 2.7

sudo: false

install:
  - pip install flake8
  - pip install tox tox-venv
  - pip install coveralls

before_script:
  - flake8 --max-line-length=100 --exclude=tests locking

env:
  - TOXENV=py27-django111
  - TOXENV=py34-django111
  - TOXENV=py34-django20
  - TOXENV=py34-django21
  - TOXENV=py35-django111
  - TOXENV=py35-django20
  - TOXENV=py35-django21
  - TOXENV=py36-django111
  - TOXENV=py36-django20
  - TOXENV=py36-django21
  - TOXENV=py37-django20
  - TOXENV=py37-django21
  - TOXENV=py27-django111-grappelli
  - TOXENV=py34-django111-grappelli
  - TOXENV=py35-django111-grappelli
  - TOXENV=py36-django111-grappelli

script:
  - travis_retry tox

after_success:
  coveralls
